version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html
    networks:
      - laravel-network
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 33060:3306
    networks:
      - laravel-network

  # You can optionally add a mail server here if needed, e.g. for testing mail sending.

networks:
  laravel-network:
    driver: bridge
